version: "3.9"

services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  backend:
    container_name: backend
    build:
      context: ./backend
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DEBUG=0
    depends_on:
      - db

#  frontend:
#    container_name: frontend
#    build:
#      context: ./frontend
#    restart: always
#    stdin_open: true
#    command: npm run build
#    depends_on:
#      - backend

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "80:8000"
    volumes:
      - static-data:/vol/static
    depends_on:
      - frontend

volumes:
  postgres-data:
  static-data: