version: "3.9"

services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  backend:
    container_name: backend
    build:
      context: ./backend
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    volumes:
      - static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    restart: always
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static-data:/vol/static
    depends_on:
      - backend

volumes:
  postgres-data:
  static-data: